import { StateSchema, MessagesValue, type GraphNode, StateGraph, START, END } from "@langchain/langgraph";
import z from "zod";
import { geminiModel, mistralAIModel, cohereModel } from "./model.ai.js";
import { createAgent, providerStrategy, HumanMessage } from 'langchain'
const State = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judgeMent: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
});

//! now i have to make node for solution 1 and solution 2 and then a node for judgement and then connect them all together in a graph

const solutionNode: GraphNode<typeof State> = async (State) => {
    const { problem } = State;
    // now we will call two model of the same problem and get two different solution and then we will pass those two solution to the judgement node and then we will get the judgement of which solution is better and why
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(problem),
        cohereModel.invoke(problem)
    ])

    // return the anser in the form of state
    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

//! now we have to make a judgement node which will take the problem and the two solution and then it will return the judgement of which solution is better and why

const judgementNode: GraphNode<typeof State> = async (State) => {
    const { problem, solution_1, solution_2 } = State;

    // here we need stict structure format resoponse so we use agent and statragey

    const agent = createAgent({
        model: geminiModel,
        //! we will use provider strategy to get the response in the form of state 
        //! becasue provider STARTEGY STRICTLY FOLLOWS THE STRUCTURE WE PROVIDE AND IT WILL ALWAYS RETURN THE RESPONSE IN THE SAME STRUCTURE SO IT IS VERY USEFUL FOR US TO GET THE JUDGEMENT IN THE FORM OF STATE
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().default(0),
            solution_2_score: z.number().default(0),
            solution_1_reasoning: z.string().default(""),
            solution_2_reasoning: z.string().default(""),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores`,
    })
    // now we will call the agent with the problem and the two solution and get the judgement
    const judgementResponse = await agent.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    })

    const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgementResponse.structuredResponse

    return {

        judgeMent: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}


// now we will create a graph and connect the nodes together

const graph = new StateGraph(State)
    .addNode("solutionNode", solutionNode)
    .addNode("judgementNode", judgementNode)
    .addEdge(START, "solutionNode")
    .addEdge("solutionNode", "judgementNode")
    .addEdge("judgementNode", END)
    .compile()

// now we can run the graph with a problem and get the solution and judgement

export default async function (problem: string) {
    const result = await graph.invoke({
        problem
    })

    return result
}

