// This file defines the "Brain" of the AI Arena using LangGraph.
// It sets up a workflow where one step generates solutions and the next step judges them.
import { StateSchema, MessagesValue, type GraphNode, StateGraph, START, END } from "@langchain/langgraph";
import z from "zod";
import { geminiModel, mistralAIModel, cohereModel } from "./model.ai.js";
import { createAgent, providerStrategy, HumanMessage } from 'langchain'
// The State defines what information we are tracking throughout the AI's "thought process".
const State = new StateSchema({
    problem: z.string().default(""), // The original problem description
    solution_1: z.string().default(""), // Solution from the first model
    solution_2: z.string().default(""), // Solution from the second model
    judgeMent: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
});

// solutionNode: This part of the brain asks two different AI models (Mistral and Cohere) 
// to solve the same problem at the same time.
const solutionNode: GraphNode<typeof State> = async (State) => {
    const { problem } = State;
    // now we will call two model of the same problem and get two different solution and then we will pass those two solution to the judgement node and then we will get the judgement of which solution is better and why
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(problem),
        cohereModel.invoke(problem)
    ])

    // return the anser in the form of state
    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

// judgementNode: This part of the brain uses the Gemini model to look at both solutions 
// and decide which one is better, giving each a score and an explanation.
const judgementNode: GraphNode<typeof State> = async (State) => {
    const { problem, solution_1, solution_2 } = State;

    // here we need stict structure format resoponse so we use agent and statragey

    const agent = createAgent({
        model: geminiModel,
        //! we will use provider strategy to get the response in the form of state 
        //! becasue provider STARTEGY STRICTLY FOLLOWS THE STRUCTURE WE PROVIDE AND IT WILL ALWAYS RETURN THE RESPONSE IN THE SAME STRUCTURE SO IT IS VERY USEFUL FOR US TO GET THE JUDGEMENT IN THE FORM OF STATE
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().default(0),
            solution_2_score: z.number().default(0),
            solution_1_reasoning: z.string().default(""),
            solution_2_reasoning: z.string().default(""),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores`,
    })
    // now we will call the agent with the problem and the two solution and get the judgement
    const judgementResponse = await agent.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    })

    const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgementResponse.structuredResponse

    return {

        judgeMent: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }
}


// Here we define the "Map" or "Flow" of how the AI should think.
// 1. Start -> 2. Generate Solutions -> 3. Judge Solutions -> 4. End
const graph = new StateGraph(State)
    .addNode("solutionNode", solutionNode)
    .addNode("judgementNode", judgementNode)
    .addEdge(START, "solutionNode")
    .addEdge("solutionNode", "judgementNode")
    .addEdge("judgementNode", END)
    .compile()

// now we can run the graph with a problem and get the solution and judgement

export default async function (problem: string) {
    const result = await graph.invoke({
        problem
    })

    return result
}

